import { LeaDashboardData } from './dashboard.models';

export const LEA_DASHBOARD_DATA: Record<string, LeaDashboardData> = {
  dcps: {
    id: 'dcps',
    orgLabel: 'DCPS',
    displayName: 'District of Columbia Public Schools',
    activeCollections: [
      {
        id: 'discipline',
        name: 'Discipline',
        status: 'success',
        statusLabel: 'Success',
        dueDate: 'Sep 15, 2026',
        recordCount: 4908,
      },
      {
        id: 'course',
        name: 'Course',
        status: 'processing',
        statusLabel: 'Processing',
        dueDate: 'Aug 19, 2026',
        recordCount: 2140,
        processingNote: 'Aug 19, 2026',
      },
      {
        id: 'clsd-lea',
        name: 'CLSD-LEA',
        status: 'overdue',
        statusLabel: 'Overdue',
        dueDate: 'Aug 25, 2025',
      },
      {
        id: 'course-phase-ii',
        name: 'Course phase II',
        status: 'not-started',
        statusLabel: 'Not started',
        dueDate: 'Dec 9, 2022',
      },
    ],
    inactiveCollections: [
      { id: 'staff', name: 'Staff', status: 'success', statusLabel: 'Closed', dueDate: 'Jun 30, 2025' },
      { id: 'assessment', name: 'Assessment', status: 'success', statusLabel: 'Closed', dueDate: 'May 15, 2025' },
      { id: 'graduation', name: 'Graduation', status: 'success', statusLabel: 'Closed', dueDate: 'Apr 1, 2025' },
      { id: 'attendance', name: 'Attendance', status: 'success', statusLabel: 'Closed', dueDate: 'Mar 10, 2025' },
      {
        id: 'enrollment-fall',
        name: 'Enrollment Fall',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Oct 5, 2024',
      },
      {
        id: 'special-ed',
        name: 'Special Education',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Sep 20, 2024',
      },
      { id: 'title-i', name: 'Title I', status: 'success', statusLabel: 'Closed', dueDate: 'Aug 1, 2024' },
    ],
    collectionDetails: {
      discipline: {
        orgLabel: 'DCPS',
        name: 'Discipline Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Passed',
        stats: [
          { label: 'Total records', value: 4908, tone: 'neutral' },
          { label: 'Passed', value: 4822, tone: 'positive' },
          { label: 'Failed', value: 54, tone: 'negative' },
          { label: 'Warnings', value: 32, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'DCPS_Enrollment_Fall2026_v3.xlsx',
          uploadedAt: 'Aug 10, 2026, 2:32 PM',
          rowCount: 4908,
          sizeKb: 2150,
          passed: true,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Fall2026_v3.xlsx', uploadedAt: 'Aug 10', rowCount: 4908, passed: true },
          { id: 's2', fileName: 'Fall2026_v2.xlsx', uploadedAt: 'Aug 6', rowCount: 4751, passed: false },
          { id: 's3', fileName: 'Fall2026_v1.xlsx', uploadedAt: 'Aug 6', rowCount: 4751, passed: false },
        ],
      },
      course: {
        orgLabel: 'DCPS',
        name: 'Course Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Passed',
        stats: [
          { label: 'Total records', value: 2140, tone: 'neutral' },
          { label: 'Passed', value: 0, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 0, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'DCPS_Course_Fall2026_v1.xlsx',
          uploadedAt: 'Aug 12, 2026, 9:14 AM',
          rowCount: 2140,
          sizeKb: 980,
          passed: true,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Course_Fall2026_v1.xlsx', uploadedAt: 'Aug 12', rowCount: 2140, passed: true },
        ],
      },
      'clsd-lea': {
        orgLabel: 'DCPS',
        name: 'CLSD-LEA Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Failed',
        stats: [
          { label: 'Total records', value: 0, tone: 'neutral' },
          { label: 'Passed', value: 0, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 0, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'No file uploaded',
          uploadedAt: '—',
          rowCount: 0,
          sizeKb: 0,
          passed: false,
        },
        submissionHistory: [],
      },
      'course-phase-ii': {
        orgLabel: 'DCPS',
        name: 'Course Phase II Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Failed',
        stats: [
          { label: 'Total records', value: 0, tone: 'neutral' },
          { label: 'Passed', value: 0, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 0, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'No file uploaded',
          uploadedAt: '—',
          rowCount: 0,
          sizeKb: 0,
          passed: false,
        },
        submissionHistory: [],
      },
    },
  },

  'kipp-dc': {
    id: 'kipp-dc',
    orgLabel: 'KIPP DC',
    displayName: 'KIPP DC Public Charter Schools',
    activeCollections: [
      {
        id: 'enrollment',
        name: 'Enrollment',
        status: 'failed',
        statusLabel: 'Failed',
        dueDate: 'Aug 5, 2026',
        recordCount: 1560,
      },
      {
        id: 'discipline-kipp',
        name: 'Discipline',
        status: 'failed',
        statusLabel: 'Failed',
        dueDate: 'Aug 12, 2026',
        recordCount: 980,
      },
      {
        id: 'attendance-kipp',
        name: 'Attendance',
        status: 'success',
        statusLabel: 'Success',
        dueDate: 'Sep 1, 2026',
        recordCount: 2100,
      },
    ],
    inactiveCollections: [
      { id: 'staff-kipp', name: 'Staff', status: 'success', statusLabel: 'Closed', dueDate: 'Jun 30, 2025' },
      { id: 'assessment-kipp', name: 'Assessment', status: 'success', statusLabel: 'Closed', dueDate: 'May 15, 2025' },
      { id: 'graduation-kipp', name: 'Graduation', status: 'success', statusLabel: 'Closed', dueDate: 'Apr 1, 2025' },
      {
        id: 'special-ed-kipp',
        name: 'Special Education',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Sep 20, 2024',
      },
      { id: 'title-i-kipp', name: 'Title I', status: 'success', statusLabel: 'Closed', dueDate: 'Aug 1, 2024' },
    ],
    collectionDetails: {
      enrollment: {
        orgLabel: 'KIPP DC',
        name: 'Enrollment Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Failed',
        stats: [
          { label: 'Total records', value: 1560, tone: 'neutral' },
          { label: 'Passed', value: 1200, tone: 'positive' },
          { label: 'Failed', value: 310, tone: 'negative' },
          { label: 'Warnings', value: 50, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'KIPP_Enrollment_Fall2026_v2.xlsx',
          uploadedAt: 'Aug 5, 2026, 10:15 AM',
          rowCount: 1560,
          sizeKb: 640,
          passed: false,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Enrollment_v2.xlsx', uploadedAt: 'Aug 5', rowCount: 1560, passed: false },
          { id: 's2', fileName: 'Enrollment_v1.xlsx', uploadedAt: 'Jul 30', rowCount: 1540, passed: false },
        ],
      },
      'discipline-kipp': {
        orgLabel: 'KIPP DC',
        name: 'Discipline Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Failed',
        stats: [
          { label: 'Total records', value: 980, tone: 'neutral' },
          { label: 'Passed', value: 770, tone: 'positive' },
          { label: 'Failed', value: 190, tone: 'negative' },
          { label: 'Warnings', value: 20, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'KIPP_Discipline_Fall2026_v1.xlsx',
          uploadedAt: 'Aug 12, 2026, 1:05 PM',
          rowCount: 980,
          sizeKb: 410,
          passed: false,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Discipline_v1.xlsx', uploadedAt: 'Aug 12', rowCount: 980, passed: false },
        ],
      },
      'attendance-kipp': {
        orgLabel: 'KIPP DC',
        name: 'Attendance Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Passed',
        stats: [
          { label: 'Total records', value: 2100, tone: 'neutral' },
          { label: 'Passed', value: 2100, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 0, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'KIPP_Attendance_Fall2026_v1.xlsx',
          uploadedAt: 'Sep 1, 2026, 8:40 AM',
          rowCount: 2100,
          sizeKb: 860,
          passed: true,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Attendance_v1.xlsx', uploadedAt: 'Sep 1', rowCount: 2100, passed: true },
        ],
      },
    },
  },

  'friendship-pcs': {
    id: 'friendship-pcs',
    orgLabel: 'Friendship PCS',
    displayName: 'Friendship Public Charter School',
    activeCollections: [
      {
        id: 'enrollment-friendship',
        name: 'Enrollment',
        status: 'success',
        statusLabel: 'Success',
        dueDate: 'Sep 10, 2026',
        recordCount: 1200,
      },
      {
        id: 'course-friendship',
        name: 'Course',
        status: 'success',
        statusLabel: 'Success',
        dueDate: 'Aug 22, 2026',
        recordCount: 640,
      },
    ],
    inactiveCollections: [
      { id: 'staff-friendship', name: 'Staff', status: 'success', statusLabel: 'Closed', dueDate: 'Jun 30, 2025' },
      {
        id: 'assessment-friendship',
        name: 'Assessment',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'May 15, 2025',
      },
      {
        id: 'graduation-friendship',
        name: 'Graduation',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Apr 1, 2025',
      },
      {
        id: 'attendance-friendship',
        name: 'Attendance',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Mar 10, 2025',
      },
      {
        id: 'special-ed-friendship',
        name: 'Special Education',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Sep 20, 2024',
      },
      {
        id: 'title-i-friendship',
        name: 'Title I',
        status: 'success',
        statusLabel: 'Closed',
        dueDate: 'Aug 1, 2024',
      },
    ],
    collectionDetails: {
      'enrollment-friendship': {
        orgLabel: 'Friendship PCS',
        name: 'Enrollment Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Passed',
        stats: [
          { label: 'Total records', value: 1200, tone: 'neutral' },
          { label: 'Passed', value: 1190, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 10, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'Friendship_Enrollment_Fall2026_v1.xlsx',
          uploadedAt: 'Sep 10, 2026, 11:20 AM',
          rowCount: 1200,
          sizeKb: 520,
          passed: true,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Enrollment_v1.xlsx', uploadedAt: 'Sep 10', rowCount: 1200, passed: true },
        ],
      },
      'course-friendship': {
        orgLabel: 'Friendship PCS',
        name: 'Course Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Passed',
        stats: [
          { label: 'Total records', value: 640, tone: 'neutral' },
          { label: 'Passed', value: 640, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 0, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'Friendship_Course_Fall2026_v1.xlsx',
          uploadedAt: 'Aug 22, 2026, 3:00 PM',
          rowCount: 640,
          sizeKb: 280,
          passed: true,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Course_v1.xlsx', uploadedAt: 'Aug 22', rowCount: 640, passed: true },
        ],
      },
    },
  },

  'udc-cc': {
    id: 'udc-cc',
    orgLabel: 'UDC-CC',
    displayName: 'University of DC Community College',
    activeCollections: [
      {
        id: 'enrollment-udc',
        name: 'Enrollment',
        status: 'success',
        statusLabel: 'Success',
        dueDate: 'Sep 5, 2026',
        recordCount: 210,
      },
    ],
    inactiveCollections: [
      { id: 'staff-udc', name: 'Staff', status: 'success', statusLabel: 'Closed', dueDate: 'Jun 30, 2025' },
      { id: 'assessment-udc', name: 'Assessment', status: 'success', statusLabel: 'Closed', dueDate: 'May 15, 2025' },
      { id: 'graduation-udc', name: 'Graduation', status: 'success', statusLabel: 'Closed', dueDate: 'Apr 1, 2025' },
    ],
    collectionDetails: {
      'enrollment-udc': {
        orgLabel: 'UDC-CC',
        name: 'Enrollment Collection',
        schoolYear: 'SY2526',
        overallStatus: 'Passed',
        stats: [
          { label: 'Total records', value: 210, tone: 'neutral' },
          { label: 'Passed', value: 210, tone: 'positive' },
          { label: 'Failed', value: 0, tone: 'negative' },
          { label: 'Warnings', value: 0, tone: 'warning' },
        ],
        lastUploadedFile: {
          id: 'f1',
          fileName: 'UDC_Enrollment_Fall2026_v1.xlsx',
          uploadedAt: 'Sep 5, 2026, 4:30 PM',
          rowCount: 210,
          sizeKb: 95,
          passed: true,
        },
        submissionHistory: [
          { id: 's1', fileName: 'Enrollment_v1.xlsx', uploadedAt: 'Sep 5', rowCount: 210, passed: true },
        ],
      },
    },
  },
};
